name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: abarichello/godot-ci@4.7.1-stable
        with:
          preset: "Desktop"
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            export/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}