name: Build

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'version number v(x.y.z)'
        required: true
        type: string
        default: 'v0.0.0'

  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: abarichello/godot-ci@4.7.1-stable
        with:
          preset: "Desktop"
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version_number || github.ref_name }}
          files: |
            export/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}